#pragma once
/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'GameClientApp_dump_SCY.exetreated.exe'
*/

#include "globals.h"
#include "idadefs.h"
#include <set>
#include <stdexcept>
#include "game.h"

#include "Atlas/STU/RTTI/STUInfo.h"
#include "Atlas/STU/RTTI/STURegistry.h"

using namespace Atlas::STU::RTTI;

//rtti addresses
namespace STU_RTTI {
	//base Types
	constexpr __int64 STUStatescriptGameEntry = 0x1766a50;
	constexpr __int64 STUStatescriptState = 0x1766e40;
	constexpr __int64 STUStatescriptCondition = 0x17669d0;
	constexpr __int64 STUStatescriptActionTerminator = 0x1766c50;
	//Auch ein StatescriptState member
	constexpr __int64 Unknown = 0x1766690;

	//Other inherits
	constexpr __int64 STUConfigVarDynamic = 0x17909e0;
	constexpr __int64 STUStatescriptOutputPlug = 0x1766bd0;
	constexpr __int64 STUStatescriptStateUXBase = 0x1759fb0;

	constexpr __int64 teStructuredData = 0x17a37b0;
};

//Name hashes
//_ suffixed means name unknown
namespace STU_NAME {
	const uint STUStatescriptOutputPlug = 0x3E490486;
	const uint STUStatescriptActionSetVar = 0x4698e4b6;
	const uint STUStatescriptStateBooleanSwitch = 0xe811ecbb;
	const uint STUStatescriptEntryGameMessage = 0xbe49a4c2;
	const uint STUConfigVarGameMessage = 0xff7876f9;
	const uint STUStatescriptStateUXScreen = 0xc739baac;
	const uint STUStatescriptStateUXBase = 0x8ba08edd;
	const uint STUStatescriptStateSubScript = 0x3db862c4;
	const uint STUStatescriptStateWait = 0x65f158da;
	const uint STUStatescriptInputPlug = 0x11d7f052;
	const uint STUStatescriptStateSwitch = 0x26367267;
	const uint STUStatescriptStateEffect = 0xffbfa88d;
	const uint STUStatescriptComponent = 0x9b38211b;
	const uint STUStatescriptStateUXHeroSelectScreen = 0x8F23FA30;
	const uint STUStatescriptStateLogicalButton = 0xff77458c;
	const uint STUConfigVarLogicalButton = 0x5c7964ff;
	const uint STUConfigVarExpression = 0xcc3a08f4;
	const uint STUStatescriptState = 0xa7213568;
	const uint STUStatescriptAction = 0x2ecefc8b;

	namespace Primitive {
		const uint32 teMtx43A = 0x6fb9880b;
		const uint32 teVec3A = 0x2357e676;
		const uint32 teVec2 = 0xf6ec8926;
		const uint32 teVec3 = 0x81ebb9b0;
		const uint32 teVec4 = 0x1f8f2c13;
		const uint32 teQuat = 0xda9494c8;
		const uint32 teColorRGB = 0x525114ab;
		const uint32 teColorRGBA = 0xa9e19537;
		const uint32 teStructuredDataDateAndTime = 0xe1b9e763;
		const uint32 teEntityID = 0xc525b48;

		const uint32 DBID = 0x20b3d5a9;
		const uint32 teUUID = 0x809899f3;
		const uint32 teString = 0xbbca304b;

		//s8 gibts nicht?
		const uint32 s16 = 0xa0119d30;
		const uint32 s32 = 0x954a3bab;
		const uint32 s64 = 0x15e6adb;

		const uint32 u8 = 0x3b9327d2;
		const uint32 u16 = 0xa49ce182;
		const uint32 u32 = 0x91c74719;
		const uint32 u64 = 0x5d31669;
		
		const uint32 f32 = 0x8fa75a30;
		const uint32 f64 = 0x1bb30b40;

		extern std::set<uint32> _all;

		inline int _primitive_size(uint32 primitive_hash) {
			switch (primitive_hash) {
			case STU_NAME::Primitive::u8:
				return 1;
			case STU_NAME::Primitive::u16:
			case STU_NAME::Primitive::s16:
				return 2;
			case STU_NAME::Primitive::u32:
			case STU_NAME::Primitive::f32:
			case STU_NAME::Primitive::s32:
			case STU_NAME::Primitive::teEntityID:
				return 4;
			case STU_NAME::Primitive::s64:
			case STU_NAME::Primitive::u64:
			case STU_NAME::Primitive::f64:
			case STU_NAME::Primitive::teVec2:
			case STU_NAME::Primitive::teStructuredDataDateAndTime:
				return 8;
			case STU_NAME::Primitive::teColorRGB:
				return 0xC;
			case STU_NAME::Primitive::teVec3:
			case STU_NAME::Primitive::teVec4:
			case STU_NAME::Primitive::teVec3A:
			case STU_NAME::Primitive::teQuat:
			case STU_NAME::Primitive::DBID:
			case STU_NAME::Primitive::teUUID:
			case STU_NAME::Primitive::teString:
			case STU_NAME::Primitive::teColorRGBA:
				return 0x10;
			case STU_NAME::Primitive::teMtx43A:
				return 0x40;
			default:
				return 0;
			}
		}
	};

	const uint STUAction_PlayEffect_ = 0x66b5f581;
	const uint STUAction_RandomFromBucket_ = 0x2501a4db;
	const uint STUAction_SendGameMsgConditional_ = 0x5bea9b4b;

	const uint Simple_Condition_ = 0xb1032daf;
	const uint Effect_To_Play_Var_ = 0x48663e64;

	//Constraint type names
	/*
	const uint OnBegin_Plug_ = 0xf1f0a36d;
	const uint Abort_Plug_ = 0xe51f3e8d;*/

	const uint Subgraph_Plug_ = 0x24ab1f0b; //All inherit from this
	const uint Subgraph_Plug_2_ = 0xb8f35b20;
	const uint ClientOnly_Subgraph_Plug_ = 0x5732771b;
	const uint ClientOnly_Subgraph_Plug_2_ = 0x26c93342;
	const uint ServerOnly_Subgraph_Plug_ = 0x4e5feee5;
	
	/*const uint Switch_Plugs_ = 0x57e931d8;
	const uint Transition_Plugs_ = 0x8f6c88d9;
	const uint UX_Plugs_ = 0xaf12fa9c;*/

	const uint STUConfigVar = 0xbfd9aadd;
	const uint STUConfigVarDynamic = 0xf8cc195d;
	const uint STUIdentifier = 0x34D7F9EE;
};


struct string_rep;
struct StatescriptStateWait;
struct STUEntityDefinition;
struct STUBase_vt;
struct STU_Object;

namespace STURegistryData {
	extern std::set<STUBase_vt*> vfptr_addresses;
	void initialize();
};

struct MisalignedResourceLoadEntry {
	__int64 resource_ptr;
	__int32 flags;
	__int32 field_C;
	__int64 resource_id;
	MisalignedResourceLoadEntry* hashlist_next;
	__int64 resource_load_entry; //NULL wenn geladen
	__int64 assetpackItem_backref; //NULL wenn geladen
	__int32 field_30;
	__int32 mutex;

	template <typename T>
	T* get_as() {
		return (T*)resource_ptr;
	}

	inline MisalignedResourceLoadEntry* align() {
		return (MisalignedResourceLoadEntry*)((__int64)this & 0xFFFFFFFFFFFFFFC0);
	}

	inline bool valid() {
		static uintptr_t INVALID_ADDR = 0xFFFFFFFFFFFFFFFF;
		return align() != nullptr && reinterpret_cast<uintptr_t>(this) != INVALID_ADDR;
	}
};

struct STUteString {
	struct STUString {
		uint hash;
		int len;
		char* buf;

		//copies value
		void set(const char* str) {
			if (buf && (__int64)buf != (globals::gameBase + 0x1454b48)) {
				ow_dealloc((__int64)buf);
			}
			buf = (char*)ow_memalloc(strlen(str));
			strcpy(buf, str);
			hash = stringHash(buf);
		}
	};

	union {
		string_rep* string_rep;
		STUString* string;
	};
	int string_type;

	const char* read() {
		switch (string_type) {
		case 0:
			return "invalid";
		case 1:
			return string_rep->get();
		case 2:
			return string->buf;
		}
	}

	void set(const char* new_value) {
		switch (string_type) {
		case 0:
			string = (STUteString::STUString*)ow_memalloc(sizeof(STUteString::STUString));
			string_type = 2;
			set(new_value);
			break;
		case 1:
			owassert(false);
			break;
		case 2:
			owassert(string);
			string->set(new_value);
			break;
		}
	}
};

struct STUBullshitListPtr {
	void* list_if_1;
	void* list_if_not_1;
};

template <typename T>
struct STUBullshitListFull {
	STUBullshitListPtr* list_ptr;
	//If flag is 1: list_if_1 is used, count is stored as a __int64 in list_if_not_1
	__int64 flag;

	int count() {
		owassert(list_ptr != nullptr);
		if (flag == 1)
			return (int)list_ptr->list_if_not_1;
		return (int)list_ptr->list_if_1;
	}
	T* list() {
		owassert(list_ptr != nullptr); //if this happens other code may be fucked
		if (flag == 1)
			return (T*)list_ptr->list_if_1;
		return (T*)list_ptr->list_if_not_1;
	}
	void set_count(int count) {
		if (flag == 1)
			(*(int*)&list_ptr->list_if_not_1) = count;
		(*(int*)&list_ptr->list_if_1) = count;
	}
	void set_list(void* list) {
		if (flag == 1)
			*(void**)&list_ptr->list_if_1 = list;
		*(void**)&list_ptr->list_if_not_1 = list;
	}
	int indexof(T item) {
		int cnt = count();
		for (int i = 0; i < cnt; i++)
			if (list()[i] == item)
				return i;
		return -1;
	}
	bool contains(T item) {
		int cnt = count();
		for (int i = 0; i < cnt; i++)
			if (list()[i] == item)
				return true;
		return false;
	}
	bool valid() {
		return !!list_ptr;
	}

	T* begin() {
		return &list()[0];
	}
	T* end() {
		return &list()[count()];
	}
};

//map value is an STU object ptr
template <typename T>
struct STUMapItem {
	uint key;
	T value;
};

template <typename T>
struct STUBullshitMapPtr {
	int count;
	int* map_unk; //size = count
	STUMapItem<T>* map;
};

//typ 1 == vodoolist???
//yo wtf
template <typename T>
struct STUBullshitMapFull {
	STUBullshitMapPtr<T>* list_ptr;
	//If flag is 1: list_if_1 is used, count is stored as a __int64 in list_if_not_1
	__int64 flag;

	int count() {
		if (flag != 2) {
			owassert(false);
			return 0;
		}
		if (!list_ptr->map_unk)
			return 0;
		return list_ptr->map_unk[list_ptr->count - 1]; //im crying 0xf17591
	}
	STUMapItem<T>* list() {
		if (flag != 2) {
			owassert(false);
			return 0;
		}
		return list_ptr->map;
	}
	STUMapItem<T>* get_by_key(uint key) {
		auto items = list();
		for (int i = 0; i < count(); i++) {
			if (items[i].key == key)
				return &items[i];
		}
	}
	/*int indexof(T item) {
		int cnt = count();
		for (int i = 0; i < cnt; i++)
			if (list()[i] == item)
				return i;
		return -1;
	}*/
	bool valid() {
		return list_ptr;
	}
};

/// Benotzt bei allen value containern geladen aus CASC. Sollte die Basis for alle statescript sachen sein.
struct STUBase_vt
{
	void(__fastcall* SomeNullsub)();
	InheritanceInfo_destructor_vt rtti;
	STUInfo* const (__fastcall* GetSTUInfo)();
	__int64(__fastcall* proxy_get_something_from_arginfo)(__int64);
	__int64(__fastcall* proxy_get_something_from_arginfo_2)(__int64 stu);
	string_rep* (__fastcall* returns_nullstr_idk)(__int64, string_rep*);
	void(__fastcall* nullsub_1)();
	__int64* (__fastcall* proxy_get_something_from_arginfo_3)(__int64*);
	__int64(__fastcall* proxy_some_more_arginfo_shit)(__int64*, __int64);
	__int64 (*ret_0)();
	__int64 (*ret_0_1)();
	__int64 (*ret_0_2)();
	__int64 (*ret_0_3)();
	__int64 (*ret_0_4)();
	void(__fastcall* field_4)();
	void(__fastcall* field_5)();
	void(__fastcall* field_6)();
	__int64(__fastcall* field_A0)(__int64*);
	__int64 (*field_7)();
	void(__fastcall* field_8)();
	__int64 (*field_9)();
	void(__fastcall* field_10)();
	char (*ret_1_0)();
};

template <typename T = STUBase_vt>
struct STUBase {
	union {
		T* vfptr;
		STUBase_vt* vfptr_stubase;
	};

	STUBase<>* as_generic() {
		return (STUBase<>*)this;
	}

	bool valid() {
		return (uintptr_t)this != 0xFFFFFFFFFFFFFFFF &&
			this &&
			!IsBadReadPtr(this, 8) &&
			((__int64)vfptr_stubase - globals::gameBase) < globals::gameSize; /*&&
			STURegistryData::vfptr_addresses.find(vfptr) != STURegistryData::vfptr_addresses.end())*/
	}

	STU_Object to_editable();
};


struct STUEnumValueDefinition {
	char* value_name;
	uint32 hash;
	__int64 value;
};

struct STUEnumDefinition {
	char* enum_name;
	uint32 __unused;
	uint32 enum_hash;
	STUEnumValueDefinition* values;
	int values_count;

	STUEnumValueDefinition* findValue(int value) {
		owassert(this);
		for (int i = 0; i < values_count; i++) {
			if ((int)values[i].value == value)
				return &values[i];
		}
		return nullptr;
	}
};

struct STU_EnumRegistry {
	STU_EnumRegistry* next;
	STUEnumDefinition* def;
};

inline STU_EnumRegistry* STUEnumRegistry() {
	return *(STU_EnumRegistry**)(globals::gameBase + 0x18f7500);
}

inline STUEnumDefinition* STUFindEnum(uint32 hash) {
	STU_EnumRegistry* registry = STUEnumRegistry();
	while (registry) {
		if (registry->def && registry->def->enum_hash == hash)
			return registry->def;
		registry = registry->next;
	}
	return nullptr;
}

struct STUResourceReference {
	MisalignedResourceLoadEntry* resource_load_entry;
	__int64 resource_id;

	bool is_resource_loaded() const {
		return *(uint64_t*)&resource_load_entry != 0xFFFFFFFFFFFFFFFFu && resource_load_entry->valid();
	}

	bool has_resource() const {
		return is_resource_loaded() || resource_id != 0;
	}

	const char* get_UXDisplayString() const {
		if (resource_id != 0)
			owassert((resource_id & 0xDE0000000000000) != 0);
		return GetUXDisplayString(resource_id);
	}

	STUBase<>* get_STU() const;
};

//can return empty, not a resload-struct but getting already loaded resource ptr
inline __int64 try_load_resource(__int64 stu_id) {
	__try {
		auto load_ent2 = (__int64(__fastcall*)(__int64))(globals::gameBase + 0x9c6470);

		return load_ent2(stu_id);
	}
	__except (EXCEPTION_EXECUTE_HANDLER) {
		printf("Exception suppressd while loading resource %p!\n", stu_id);
	}
	return 0;
}

inline MisalignedResourceLoadEntry* try_load_resource_2(__int64 stu_id) {
	__try {
		typedef int (*fn)(MisalignedResourceLoadEntry**, __int64);
		fn resource_load = (fn)(globals::gameBase + 0x9c8330);

		MisalignedResourceLoadEntry* result_var;
		__int64 entity_def = resource_load(&result_var, stu_id);
		return result_var;
	}
	__except (EXCEPTION_EXECUTE_HANDLER) {
		printf("Exception suppressd while loading (2) resource %p!\n", stu_id);
	}
	return 0;
}