# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MinGW

on:
  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      name: clone
      with:
        submodules: recursive
        
    - uses: cachix/install-nix-action@v31
      name: install nix
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: disk check 2
      run: "df -h"
    
    - name: build
      run: "nix --extra-experimental-features 'nix-command flakes' develop .#build --command true"

    - name: zip
      run: "zip output.zip output/Release/bin/*"
    
    - name: upload
      shell: bash
      run: |
        curl -X PUT -H "PW: $CI_UPLOAD_TOKEN" --data-binary @output.zip https://cdn.owdev.wiki/ci/prometheus/$GITHUB_REF_NAME/prometheus-$(date -u +'%Y-%m-%dT%H:%M:%S')-${GITHUB_SHA::7}.zip
      env: # Or as an environment variable
        CI_UPLOAD_TOKEN: ${{ secrets.CI_UPLOAD_TOKEN }}
