# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MinGW

on:
  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      name: clone
      with:
        submodules: recursive
    - name: init nix
      # You may pin to the exact commit or the version.
      # uses: aldoborrero/use-nix-action@2e52fec86f4d463a27615bd4a1551dd38bda361e
      uses: spotdemo4/nix-init@v1.0.0
      
    - name: build
      run: "nix --extra-experimental-features 'nix-command flakes' develop .#build"
